"stages":
- "test"
- "build"
- "publish"
- "release"
variables:
  CHART_VERSION:
    value: "2.0.0-RC0"
    description: "this string will be used as the Helm Chart Version Property"
"build":
  image:
    name: "gradle:7.2.0-jdk11"
  stage: "build"
  artifacts:
    paths:
    - "app/build/libs/genre-police.jar"
  rules:
  - if: "$CI_COMMIT_BRANCH =~ /^dev$/"
  - if: "$CI_COMMIT_BRANCH =~ /^master$/"
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+-RC\\d+$/ && $CI_PIPELINE_SOURCE =~\
      \ /^push$/"
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+$/ && $CI_PIPELINE_SOURCE =~ /^push$/"
  script:
  - "gradle build"
"docker-build":
  image:
    name: "docker"
  stage: "build"
  services:
  - name: "docker:dind"
  needs:
  - job: "build"
  rules:
  - if: "$CI_COMMIT_BRANCH =~ /^dev$/"
  - if: "$CI_COMMIT_BRANCH =~ /^master$/"
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+-RC\\d+$/ && $CI_PIPELINE_SOURCE =~\
      \ /^push$/"
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+$/ && $CI_PIPELINE_SOURCE =~ /^push$/"
  script:
  - "docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA ./app"
  - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - "docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
"docker-publish-dev":
  image:
    name: "docker"
  stage: "publish"
  services:
  - name: "docker:dind"
  needs:
  - job: "docker-build"
  rules:
  - if: "$CI_COMMIT_BRANCH =~ /^dev$/"
  script:
  - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  - "docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA rbbl/genre-police:dev"
  - "docker login -u $DOCKERHUB_USER -p $DOCKERHUB_ACCESS_TOKEN docker.io"
  - "docker push rbbl/genre-police:dev"
"docker-publish-master":
  image:
    name: "docker"
  stage: "publish"
  services:
  - name: "docker:dind"
  needs:
  - job: "docker-build"
  rules:
  - if: "$CI_COMMIT_BRANCH =~ /^master$/"
  script:
  - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  - "docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA rbbl/genre-police:latest"
  - "docker login -u $DOCKERHUB_USER -p $DOCKERHUB_ACCESS_TOKEN docker.io"
  - "docker push rbbl/genre-police:latest"
"docker-publish-release-candidate":
  image:
    name: "docker"
  stage: "publish"
  services:
  - name: "docker:dind"
  needs:
  - job: "docker-build"
  rules:
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+-RC\\d+$/ && $CI_PIPELINE_SOURCE =~\
      \ /^push$/"
  script:
  - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  - "docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA rbbl/genre-police:$CI_COMMIT_TAG"
  - "docker login -u $DOCKERHUB_USER -p $DOCKERHUB_ACCESS_TOKEN docker.io"
  - "docker push rbbl/genre-police:$CI_COMMIT_TAG"
"docker-publish-release":
  image:
    name: "docker"
  stage: "publish"
  services:
  - name: "docker:dind"
  needs:
  - job: "docker-build"
  rules:
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+$/ && $CI_PIPELINE_SOURCE =~ /^push$/"
  script:
  - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  - "docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA rbbl/genre-police:$CI_COMMIT_TAG"
  - "docker login -u $DOCKERHUB_USER -p $DOCKERHUB_ACCESS_TOKEN docker.io"
  - "docker push rbbl/genre-police:$CI_COMMIT_TAG"
".helm":
  image:
    name: "fedora"
  stage: "publish"
  before_script:
  - "dnf in -y openssl"
  - "curl -L -O https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}\
    \ && mv ${BINARY} /usr/bin/yq && chmod +x /usr/bin/yq"
  - "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
  - "chmod 700 get_helm.sh"
  - "./get_helm.sh"
  - "yq -i \".appVersion = \\\"$CI_COMMIT_TAG\\\"\" helm/genre-police/Chart.yaml"
  - "yq -i \".version = \\\"$CHART_VERSION\\\"\" helm/genre-police/Chart.yaml"
  - "cat helm/genre-police/Chart.yaml"
  - "helm repo add bitnami https://charts.bitnami.com/bitnami"
  - "helm dependency build helm/genre-police"
  - "helm package helm/genre-police"
"helm-publish-release":
  extends:
  - ".helm"
  rules:
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+-RC\\d+$/ && $CI_PIPELINE_SOURCE =~\
      \ /^web$/"
  script:
  - "curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form \"chart=@genre-police-$CHART_VERSION.tgz\"\
    \ ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
"helm-publish-release-candidate":
  extends:
  - ".helm"
  rules:
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+$/ && $CI_PIPELINE_SOURCE =~ /^web$/"
  script:
  - "curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form \"chart=@genre-police-$CHART_VERSION.tgz\"\
    \ ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/dev/charts"
"create-release":
  image:
    name: "registry.gitlab.com/gitlab-org/release-cli:latest"
  stage: "release"
  rules:
  - if: "$CI_COMMIT_TAG =~ /^\\d+\\.\\d+\\.\\d+$/ && $CI_PIPELINE_SOURCE =~ /^push$/"
  script:
  - "echo 'Running the release job.'"
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "$CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG"