stages:
  - build
  - docker
  - helm

build:
  stage: build
  image: gradle:7.2.0-jdk11
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/genre-police.jar

.docker:
  stage: docker
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.release:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

.release-candidate:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-RC\d+$/'

docker-build:
  extends: .docker
  needs:
    - build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-RC\d+$/'
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

docker-publish-release:
  needs:
    - docker-build
  extends:
    - .docker
    - .release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA rbbl/genre-police:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA rbbl/genre-police:latest
    - docker push rbbl/genre-police:$CI_COMMIT_TAG
    - docker push rbbl/genre-police:latest

docker-publish-release-candidate:
  needs:
    - docker-build
  extends:
    - .docker
    - .release-candidate
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA rbbl/genre-police:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA rbbl/genre-police:dev
    - docker push rbbl/genre-police:$CI_COMMIT_TAG
    - docker push rbbl/genre-police:dev

.helm:
  stage: helm
  image: fedora
  before_script:
    - dnf in -y openssl
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    - helm package helm/genre-police
    - mv genre-police-*.tgz genre-police.tgz

helm-publish-release:
  stage: helm
  extends:
    - .release
    - .helm
  script:
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@genre-police.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'

helm-publish-release-candidate:
  stage: helm
  extends:
    - .release-candidate
    - .helm
  script:
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@genre-police.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/dev/charts"'
