apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genre-police.fullname" . }}
  labels:
    {{- include "genre-police.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.genre_police.replicaCount }}
  selector:
    matchLabels:
      {{- include "genre-police.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.genre_police.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "genre-police.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.genre_police.image.repository }}:{{ .Values.genre_police.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.genre_police.image.pullPolicy }}
          env:
            - name: DISCORD_TOKEN
              value: {{ quote .Values.genre_police.settings.DISCORD_TOKEN }}
            - name: SPOTIFY_CLIENT_ID
              value: {{ quote .Values.genre_police.settings.SPOTIFY_CLIENT_ID }}
            - name: SPOTIFY_CLIENT_SECRET
              value: {{ quote .Values.genre_police.settings.SPOTIFY_CLIENT_SECRET }}
            {{ if not .Values.db.enabled}}
            - name: JDBC_URL
              value: {{ quote .Values.genre_police.settings.JDBC_URL }}
            - name: DB_USER
              value: {{ quote .Values.genre_police.settings.DB_USER }}
            - name: DB_PASSWORD
              value: {{ quote .Values.genre_police.settings.DB_PASSWORD }}
            {{ else }}
            - name: JDBC_URL
              value: jdbc:postgresql://{{ include "genre-police.fullname" . }}-db:5432/{{ .Values.db.settings.POSTGRES_DB }}
            - name: DB_USER
              value: {{ quote .Values.db.settings.POSTGRES_USER }}
            - name: DB_PASSWORD
              value: {{ quote .Values.db.settings.POSTGRES_PASSWORD }}
            {{ end }}
          resources:
            {{- toYaml .Values.genre_police.resources | nindent 12 }}
      {{- with .Values.genre_police.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.genre_police.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.genre_police.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

{{ if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genre-police.fullname" . }}-db
  labels:
  {{- include "genre-police.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
  {{- include "genre-police.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "genre-police.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: "postgres"
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: {{ quote .Values.db.settings.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.db.settings.POSTGRES_PASSWORD}}
            - name: POSTGRES_DB
              value: {{ quote .Values.db.settings.POSTGRES_DB}}
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: db-volume-claim
      volumes:
        - name: db-volume-claim
          persistentVolumeClaim:
            claimName: {{ include "genre-police.fullname" . }}-db-volume
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
{{ end }}