apiVersion: v1
kind: Service
metadata:
  name: {{ include "genre-police.fullname" . }}
  labels:
    {{- include "genre-police.labels" . | nindent 4 }}
spec:
  type: {{ .Values.genre_police.service.type }}
  ports:
    - port: {{ .Values.genre_police.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "genre-police.selectorLabels" . | nindent 4 }}
