{{ if .Values.db.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genre-police.fullname" . }}-db
  labels:
    {{- include "genre-police.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: "postgres"
  selector:
    {{- include "genre-police.selectorLabels" . | nindent 4 }}
  {{ end }}